// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abrjvjqjsdttlbznyjvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFicmp2anFqc2R0dGxiem55anZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTI4OTUsImV4cCI6MjA2MjIyODg5NX0.PUbiZFa7vdp_crwLrkO9AwBXMMWv3v354Whn26Q1xaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);